export { default as Google } from './Google'
export { default as Instagram } from './Instagram'
export { default as Pintrest } from './Pintrest'
export { default as Twitter } from './Twitter'
export { default as Facebook } from './Facebook'